# Generated by Django 5.0 on 2023-12-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_phone_alter_members_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='lastname',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
