# Generated by Django 5.0 on 2023-12-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_joined_date_alter_members_lastname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
